---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bgd
  name: bgd
  namespace: bgd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgd
  strategy: {}
  template:
    metadata:
      creationTimeStamp: null
      labels:
        app: bgd
    spec:
      containers:
      - image: jiwooooo0/bdg:1.0.0
        name: bdg
        env:
        - name: COLOR
          value: "blue"
        resources: {}
---